name: this is cowsay workflow

on: push

jobs:
    cowsay_job:
        runs-on: ubuntu-latest
        steps:
        - name: install the cowsay
          run: sudo apt-get install cowsay -y

        - name: ececute the cowsay commnad
          run: cowsay -f dragon "run for cover, Iam a dragon" >>dragon.txt

        - name: "check the file is exists or not"
          run: |
            grep -i "dragon" "dragon.txt"




