name: this is cowsay workflow

on: push

jobs:
    cowsay_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout the code
          uses: actions/checkout@v4

        - name: list the files
          run: ls -ltra
              
        - name: "Execute the shell script"
          run: ./myshell.sh


